site_name: Brewing Intelligence
site_url: https://abhijitmore.github.io/BrewingIntelligence/
repo_url: https://github.com/AbhijitMore/BrewingIntelligence/
repo_name: AbhijitMore/BrewingIntelligence
nav:
  - Home:
    - index.md
  - Python:
    - Python/Basics.md
    - Python/Modules and Packages.md
    - Python/Object Oriented Programming.md
    - Python/Advanced Python.md
    - Python/Handling Database.md
    - Python/Network and Security.md
    - Python/Web Scraping.md
  - Programming:
    - Data Structures:
      - Programming/Data Structures/List.md
      - Programming/Data Structures/Linked List.md
      - Programming/Data Structures/Stack.md
      - Programming/Data Structures/Queue.md
      - Programming/Data Structures/Deque.md
      - Programming/Data Structures/Hashing.md
      - Programming/Data Structures/Tree.md
      - Programming/Data Structures/Binary Search Tree.md
      - Programming/Data Structures/Heap.md
      - Programming/Data Structures/Trie.md
      - Programming/Data Structures/Graph.md
    - Algorithmic Concepts:
      - Programming/Algorithmic Concepts/Searching.md
      - Programming/Algorithmic Concepts/Sorting.md
      - Programming/Algorithmic Concepts/Recursion.md
    - DSA Patterns:
      - Programming/DSA Patterns/00. Prefix Sum.md
      - Programming/DSA Patterns/01. Bit Manipulation.md
      - Programming/DSA Patterns/02. Two Pointers.md
      - Programming/DSA Patterns/03. Fast and Slow Pointers.md
      - Programming/DSA Patterns/04. Sliding Window.md
      - Programming/DSA Patterns/05. Merge Intervals.md
      - Programming/DSA Patterns/06. Greedy Algorithm.md
      - Programming/DSA Patterns/07. Divide and Conquer.md
      - Programming/DSA Patterns/08. Dynamic Programming.md
      - Programming/DSA Patterns/09. Backtracking.md
      - Programming/DSA Patterns/10. Union Find (Disjoint Set Union - DSU).md
      - Programming/DSA Patterns/11. Segment Tree.md
      - Programming/DSA Patterns/12. KMP Algorithm.md
      - Programming/DSA Patterns/13. Rabin-Karp Algorithm.md
      - Programming/DSA Patterns/14. Z Algorithm.md
      - Programming/DSA Patterns/15. Boyer-Moore Voting Algorithm.md
    - Design Patterns:
      - Programming/Design Patterns/Behavioural.md
      - Programming/Design Patterns/Creational.md
      - Programming/Design Patterns/Structural.md
    - System Design:
      - Programming/System Design/Introduction.md
    - Software Architecture Patterns:
      - Programming/Software Architecture Patterns/Introduction.md
  - Data Analysis:
    - Data Analysis/NumPy.md
    - Data Analysis/Scipy.md
    - Data Analysis/Pandas.md
    - Data Analysis/Polars.md
    - Visualization:
      - Data Analysis/Matplotlib.md
      - Data Analysis/Seaborn.md
      - Data Analysis/Plotly.md
      - Data Analysis/Bokeh.md
    - Handling Images:
      - Data Analysis/OpenCV.md
      - Data Analysis/PIL.md
  - Machine Learning:
    - Data Preprocessing:
      - Machine Learning/Data Preprocessing/Handling Missing Data.md
      - Machine Learning/Data Preprocessing/Data Cleaning.md
      - Machine Learning/Data Preprocessing/Feature Scaling.md
      - Machine Learning/Data Preprocessing/Feature Engineering.md
      - Machine Learning/Data Preprocessing/Feature Selection.md
      - Machine Learning/Data Preprocessing/Handling Categorical Data.md
      - Machine Learning/Data Preprocessing/Data Splitting.md
      - Machine Learning/Data Preprocessing/Dimensionality Reduction.md
    - Models:
      - Machine Learning/Models/Linear Regression.md
      - Machine Learning/Models/Logistic Regression.md
      - Machine Learning/Models/Naive Bayes.md
      - Machine Learning/Models/K-Nearest Neighbours.md
      - Machine Learning/Models/Support Vector Machine.md
      - Machine Learning/Models/Decision Tree.md
      - Machine Learning/Models/Ensemble Techniques.md
      - Machine Learning/Models/Dimensionality Reduction.md
      - Machine Learning/Models/Clustering.md
      - Machine Learning/Models/Recommendation Systems.md
    - Model Evaluation and Validation:
      - Machine Learning/Model Evaluation and Validation/Cross-Validation Techniques.md
      - Machine Learning/Model Evaluation and Validation/Performance Metrics for Classification.md
      - Machine Learning/Model Evaluation and Validation/Performance Metrics for Regression.md
      - Machine Learning/Model Evaluation and Validation/Bias-Variance Tradeoff.md
      - Machine Learning/Model Evaluation and Validation/Hyperparameter Tuning.md
  - Deep Learning:
    - Deep Learning/Neural Networks Basics.md 
    - Deep Learning/Optimization Algorithms.md
    - Deep Learning/Training Deep Networks.md
    - Computer Vision:
      - Deep Learning/Image Classification.md 
      - Deep Learning/Object Detection.md 
      - Deep Learning/Segmentation.md
      - Deep Learning/Keypoint Detection.md
      - Deep Learning/Optical Flow.md
    - Natual Language Processing:
      - Deep Learning/RNN.md
      - Deep Learning/LSTM.md
      - Deep Learning/GRU.md
  - Gen AI:
    - Gen AI/Restricted Boltzmann Machines.md
    - Gen AI/Variational Autoencoders.md
    - Gen AI/Generative Adverserial Network.md
    - Gen AI/Diffusion Models.md
    - Gen AI/Transformers.md
    - Gen AI/RAGs.md
    - Gen AI/Agents.md
  - DevOps:
    - DevOps/Shell.md
    - DevOps/Git.md
    - DevOps/package manager and virtual environment.md
    - DevOps/Publishing Python Packages.md
    - DevOps/Documentation, Styling and Pre-commit.md
    - DevOps/Logging.md
    - DevOps/Build Systems.md
    - DevOps/Continuous Integration.md
    - DevOps/Flask.md
    - DevOps/Docker.md
    - DevOps/Mlflow.md
    - DevOps/ZenML.md
  - Data Engineering:
    - Data Engineering/Spark.md
    - Data Engineering/Kafka.md
    - Data Engineering/Flink.md

theme:
  custom_dir: brew_env/lib/python3.12/site-packages/material/overrides
  features:
    - navigation.tabs
    - navigation.footer
    - content.code.copy
    - content.code.annotate
  name: material
  font: 
    text: Epilogue
    code: Roboto Mono
  favicon: assets/brain-solid.ico
  logo: assets/brain-solid.svg
  icon:  
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode


markdown_extensions:
  - tables
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  # - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


extra:
  social:
    - icon: simple/linkedin
      link: https://linkedin.com/in/hey-abhijit-more
    - icon: fontawesome/brands/github
      link: https://github.com/AbhijitMore
    - icon: fontawesome/regular/envelope-open
      link: mailto:abhimore@gmail.com

copyright: Copyright &copy; 2025 Abhijit More