site_name: Brewing Intelligence
site_url: https://abhijitmore.github.io/BrewingIntelligence/
repo_url: https://github.com/AbhijitMore/BrewingIntelligence/
repo_name: AbhijitMore/BrewingIntelligence
nav:
  - Home:
    - index.md
  - Python:
    - Python Basics:
      - Python/Python Basics/Python Language Fundamentals.md
      - Python/Python Basics/Operators.md
      - Python/Python Basics/Control Flow.md
      - Python/Python Basics/Data Structures.md
      - Python/Python Basics/Strings.md
      - Python/Python Basics/Functions and Code Reuse.md
      - Python/Python Basics/Basic Error Handling.md
      - Python/Python Basics/The Python Environment.md
      - Python/Python Basics/Introdicion to OOPs.md
      - Python/Python Basics/Basic Built-in Functions and Libraries.md
    - Python Intermediate:
      - Python/Python Intermediate/Intermediate Syntax and Structures.md
      - Python/Python Intermediate/Functions and Scope.md
      - Python/Python Intermediate/Modules and Packages.md
      - Python/Python Intermediate/Error Handling.md
      - Python/Python Intermediate/File Handling.md
      - Python/Python Intermediate/Data Handling and Standard Library.md
      - Python/Python Intermediate/Classes and OOP Basics.md
    - Python Advanced:
      - Advanced Functions:
        - Python/Python Advanced/Advanced Functions/Closures.md
        - Python/Python Advanced/Advanced Functions/Decorators.md
        - Python/Python Advanced/Advanced Functions/Higher Order Functions.md
        - Python/Python Advanced/Advanced Functions/Lambda Functions.md
        - Python/Python Advanced/Advanced Functions/Partial Functions.md
        - Python/Python Advanced/Advanced Functions/Function Annotations and Type Hints.md
        - Python/Python Advanced/Advanced Functions/Parameter Unpacking.md
        - Python/Python Advanced/Advanced Functions/Variable Scope and nonlocal Keywords.md
        - Python/Python Advanced/Advanced Functions/Callable Objects.md
      - Object Oriented Programming:
        - Python/Python Advanced/Object Oriented Programming/@property Decorators.md
        - Python/Python Advanced/Object Oriented Programming/Abstract Base Classes.md
        - Python/Python Advanced/Object Oriented Programming/Class Methods and Static Methods.md
        - Python/Python Advanced/Object Oriented Programming/Dunder or Magic Methods.md
        - Python/Python Advanced/Object Oriented Programming/Encapsulation and Access Modifiers.md
        - Python/Python Advanced/Object Oriented Programming/Inheritance and Multiple Inheritance.md
        - Python/Python Advanced/Object Oriented Programming/Method Resolution Order.md
        - Python/Python Advanced/Object Oriented Programming/Polymorphism.md
      - Meta Programming:
        - Python/Python Advanced/Meta Programming/Metaclasses.md
        - Python/Python Advanced/Meta Programming/type() for Dynamic Class Creation.md
        - Python/Python Advanced/Meta Programming/Inspect Module for Introspection.md
        - Python/Python Advanced/Meta Programming/Monkey Patching.md
        - Python/Python Advanced/Meta Programming/Code Generations using exec() and eval().md
        - Python/Python Advanced/Meta Programming/Class Decorators.md
      - Iterarators, Generators and Coroutines:
        - Python/Python Advanced/Iterarators, Generators and Coroutines/Custom Iterators.md
      - Concurrency and Parallelism:
        - Python/Python Advanced/Concurrency and Parallelism/Threading.md
      - Data Model and Customization:
        - Python/Python Advanced/Data Model and Customization/Custom Containers.md
      - Functional Programming:
        - Python/Python Advanced/Functional Programming/Map, Filter and Reduce.md
      - Modules and Packaging:
        - Python/Python Advanced/Modules and Packaging/Creating Modules and Packages.md
      - Memory Management and Performance:
        - Python/Python Advanced/Memory Management and Performance/Reference Counting.md
      - Typing and Static Analysis:
        - Python/Python Advanced/Typing and Static Analysis/Type Hints and Annotations.md
      - File and Data Handling:
        - Python/Python Advanced/File and Data Handling/File IO.md
      - Network and Web Programming:
        - Python/Python Advanced/Network and Web Programming/HTTP Requests.md
      - Testing and Debugging:
        - Python/Python Advanced/Testing and Debugging/Unit Testing.md
      - Python Internals:
        - Python/Python Advanced/Python Internals/Global Interpreter Lock.md
      - Security and Safe Practices:
        - Python/Python Advanced/Security and Safe Practices/Managing Secrets.md
      - New Python Features and Enhancements:
        - Python/Python Advanced/New Python Features and Enhancements/New Syntax and Features.md
      - Advanced Use Cases and Applications:
        - Python/Python Advanced/Advanced Use Cases and Applications/Building Command Line Interfaces.md
  - Programming:
    - Data Structures:
      - Programming/Data Structures/List.md
      - Programming/Data Structures/Linked List.md
      - Programming/Data Structures/Stack.md
      - Programming/Data Structures/Queue.md
      - Programming/Data Structures/Deque.md
      - Programming/Data Structures/Hashing.md
      - Programming/Data Structures/Tree.md
      - Programming/Data Structures/Binary Search Tree.md
      - Programming/Data Structures/Heap.md
      - Programming/Data Structures/Trie.md
      - Programming/Data Structures/Graph.md
    - Algorithmic Concepts:
      - Programming/Algorithmic Concepts/Searching.md
      - Programming/Algorithmic Concepts/Sorting.md
      - Programming/Algorithmic Concepts/Recursion.md
    - DSA Patterns:
      - Programming/DSA Patterns/00. Prefix Sum.md
      - Programming/DSA Patterns/01. Bit Manipulation.md
      - Programming/DSA Patterns/02. Two Pointers.md
      - Programming/DSA Patterns/03. Fast and Slow Pointers.md
      - Programming/DSA Patterns/04. Sliding Window.md
      - Programming/DSA Patterns/05. Merge Intervals.md
      - Programming/DSA Patterns/06. Greedy Algorithm.md
      - Programming/DSA Patterns/07. Divide and Conquer.md
      - Programming/DSA Patterns/08. Dynamic Programming.md
      - Programming/DSA Patterns/09. Backtracking.md
      - Programming/DSA Patterns/10. Union Find (Disjoint Set Union - DSU).md
      - Programming/DSA Patterns/11. Segment Tree.md
      - Programming/DSA Patterns/12. String Matching Patterns.md
      - Programming/DSA Patterns/13. Boyer-Moore Voting Algorithm.md
    - Design Patterns:
      - Programming/Design Patterns/Behavioural.md
      - Programming/Design Patterns/Creational.md
      - Programming/Design Patterns/Structural.md
    - System Design:
      - Programming/System Design/Introduction.md
    - Software Architecture Patterns:
      - Programming/Software Architecture Patterns/Introduction.md
  - Data Analysis:
    - Data Analysis/NumPy.md
    - Data Analysis/Scipy.md
    - Data Analysis/Pandas.md
    - Data Analysis/Polars.md
    - Visualization:
      - Data Analysis/Matplotlib.md
      - Data Analysis/Seaborn.md
      - Data Analysis/Plotly.md
      - Data Analysis/Bokeh.md
    - Handling Images:
      - Data Analysis/OpenCV.md
      - Data Analysis/PIL.md
  - Machine Learning:
    - Data Preprocessing:
      - Machine Learning/Data Preprocessing/Handling Missing Data.md
      - Machine Learning/Data Preprocessing/Data Cleaning.md
      - Machine Learning/Data Preprocessing/Feature Scaling.md
      - Machine Learning/Data Preprocessing/Feature Engineering.md
      - Machine Learning/Data Preprocessing/Feature Selection.md
      - Machine Learning/Data Preprocessing/Handling Categorical Data.md
      - Machine Learning/Data Preprocessing/Data Splitting.md
      - Machine Learning/Data Preprocessing/Dimensionality Reduction.md
    - Models:
      - Machine Learning/Models/Linear Regression.md
      - Machine Learning/Models/Logistic Regression.md
      - Machine Learning/Models/Naive Bayes.md
      - Machine Learning/Models/K-Nearest Neighbours.md
      - Machine Learning/Models/Support Vector Machine.md
      - Machine Learning/Models/Decision Tree.md
      - Machine Learning/Models/Ensemble Techniques.md
      - Machine Learning/Models/Dimensionality Reduction.md
      - Machine Learning/Models/Clustering.md
      - Machine Learning/Models/Recommendation Systems.md
    - Model Evaluation and Validation:
      - Machine Learning/Model Evaluation and Validation/Cross-Validation Techniques.md
      - Machine Learning/Model Evaluation and Validation/Performance Metrics for Classification.md
      - Machine Learning/Model Evaluation and Validation/Performance Metrics for Regression.md
      - Machine Learning/Model Evaluation and Validation/Bias-Variance Tradeoff.md
      - Machine Learning/Model Evaluation and Validation/Hyperparameter Tuning.md
  - Deep Learning:
    - Deep Learning/Neural Networks Basics.md 
    - Deep Learning/Optimization Algorithms.md
    - Deep Learning/Training Deep Networks.md
    - Computer Vision:
      - CNN Architectures:
        - Deep Learning/LeNet-5.md
        - Deep Learning/AlexNet.md
        - Deep Learning/VGGNet.md
        - Deep Learning/GoogLeNet-Inception.md
        - Deep Learning/ResNet.md
        - Deep Learning/MobileNet.md
        - Deep Learning/XceptionNet.md
        - Deep Learning/SqueezeNet.md
        - Deep Learning/DenseNet.md
        - Deep Learning/ShuffleNet.md
        - Deep Learning/Cnn Evolution.md
      - Deep Learning/Object Detection.md 
      - Deep Learning/Segmentation.md
      - Deep Learning/Keypoint Detection.md
      - Deep Learning/Optical Flow.md
    - Natual Language Processing:
      - Deep Learning/RNN.md
      - Deep Learning/LSTM.md
      - Deep Learning/GRU.md
  - Gen AI:
    - Gen AI/Restricted Boltzmann Machines.md
    - Gen AI/Variational Autoencoders.md
    - Gen AI/Generative Adverserial Network.md
    - Gen AI/Diffusion Models.md
    - Gen AI/Transformers.md
    - Gen AI/RAGs.md
    - Gen AI/Agents.md
  - DevOps:
    - DevOps/Shell.md
    - DevOps/Git.md
    - DevOps/package manager and virtual environment.md
    - DevOps/Publishing Python Packages.md
    - DevOps/Documentation, Styling and Pre-commit.md
    - DevOps/Logging.md
    - DevOps/Build Systems.md
    - DevOps/Continuous Integration.md
    - DevOps/Flask.md
    - DevOps/Docker.md
    - DevOps/Mlflow.md
    - DevOps/ZenML.md
    - AI Inference & Acceleration Stack:
      - DevOps/CUDA and cuDNN.md
      - DevOps/Inference Optimization Engines.md
      - DevOps/Inference Serving Frameworks.md
      - DevOps/Edge Hardware Platform.md
  - Data Engineering:
    - Data Engineering/Spark.md
    - Data Engineering/Kafka.md
    - Data Engineering/Flink.md

theme:
  custom_dir: brew_env/lib/python3.12/site-packages/material/overrides
  features:
    - navigation.tabs
    - navigation.footer
    - content.code.copy
    - content.code.annotate
  name: material
  font: 
    text: Epilogue
    code: Roboto Mono
  favicon: assets/brain-solid.ico
  logo: assets/brain-solid.svg
  icon:  
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode


markdown_extensions:
  - tables
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  # - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


extra:
  social:
    - icon: simple/linkedin
      link: https://linkedin.com/in/hey-abhijit-more
    - icon: fontawesome/brands/github
      link: https://github.com/AbhijitMore
    - icon: fontawesome/regular/envelope-open
      link: mailto:abhimore@gmail.com

copyright: Copyright &copy; 2025 Abhijit More